name: "axion - AI in Action"
description: "GitHub Action for seamless AI integration with multiple providers (OpenAI, Anthropic, Groq, Mistral, etc) to enhance workflows."
author: "https://github.com/0xjord4n"

inputs:
  config:
    description: "Config to use for the action"
    required: true

outputs:
  text:
    description: "Generated text response"
  usage:
    description: "Usage information from the provider"
  finishReason:
    description: "Reason the generation finished"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  color: "purple"
  icon: "compass"
