name: "axion - AI in Action"
description: "GitHub Action for AI integration with multiple providers (OpenAI, Anthropic, Groq, etc) to enhance your workflows."
author: "https://github.com/0xjord4n"

inputs:
  config:
    description: "Config to use for the action"
    required: true

outputs:
  text:
    description: "Generated text response"
  usage:
    description: "Usage information from the provider"
  finishReason:
    description: "Reason the generation finished"

runs:
  using: "node20"
  main: "dist/index.js"

branding:
  color: "purple"
  icon: "compass"
